baseURL = "https://www.clubdelecture.nyc"
languageCode = "en-us"
title = "Club de lecture NYC"
theme = "yourfolio"
disableKinds = [ "RSS", "taxonomy", "taxonomyTerm" ]
#UA ID UA-91453506-2 #
googleAnalytics = "G-40FQVRP3Q7"
#GA4 ID G-40FQVRP3Q7 #



[[menu.main]]
name = "Contact"
weight = 2
url = "/contact"

[params]
env = "development"
logoImage = "/bookmark-logo.png"
logoImageAlt = "Club de lecture NYC logo"
